# generated from catkin/cmake/template/pkgConfig-version.cmake.in
<<<<<<< HEAD
set(PACKAGE_VERSION "1.3.2")
=======
set(PACKAGE_VERSION "1.3.1")
>>>>>>> 5dde3504395d94e94f2136ce73dd1610335c4702

set(PACKAGE_VERSION_EXACT False)
set(PACKAGE_VERSION_COMPATIBLE False)

if("${PACKAGE_FIND_VERSION}" VERSION_EQUAL "${PACKAGE_VERSION}")
  set(PACKAGE_VERSION_EXACT True)
  set(PACKAGE_VERSION_COMPATIBLE True)
endif()

if("${PACKAGE_FIND_VERSION}" VERSION_LESS "${PACKAGE_VERSION}")
  set(PACKAGE_VERSION_COMPATIBLE True)
endif()
