grid_map_filters:
  filter_chain:
  # Compute surface normals.
    - name: surface_normals
      type: gridMapFilters/NormalVectorsFilter
      params:
        input_layer: elevation
        algorithm: raster
        output_layers_prefix: normal_
        radius: 0.05
        normal_vector_positive_axis: z
        parallelization_enabled: true
        thread_number: 4

#   # Add a color layer for visualization based on the surface normal.
#     # - name: normal_color_map
#     #   type: gridMapFilters/NormalColorMapFilter
#     #   params:
#     #     input_layers_prefix: normal_vectors_
#     #     output_layer: normal_color


# grid_map_filters:
#   filter_chain:
#   # Compute surface normals.
#     - 
#       name: surface_normals_area
#       type: gridMapFilters/NormalVectorsFilter
#       params:
#         input_layer: elevation
#         algorithm: area
#         output_layers_prefix: normal_area_
#         radius: 0.05
#         normal_vector_positive_axis: z
#         parallelization_enabled: true
#         thread_number: 4
#         # thread_number: -1 doesn't limit the number of threads to be used

#     - 
#       name: surface_normals_raster
#       type: gridMapFilters/NormalVectorsFilter
#       params:
#         input_layer: elevation
#         algorithm: raster
#         output_layers_prefix: normal_raster_
#         normal_vector_positive_axis: z
#         parallelization_enabled: true
#         thread_number: 4