grid_map_topic: /grid_map_filter_demo/filtered_map
grid_map_visualizations:
    - name: surface_normals
      type: vectors
      params:
        layer_prefix: normal_
        position_layer: elevation
        scale: 0.06
        line_width: 0.005
        color: 15600153 # red
    - name: surface_normals_analytic
      type: vectors
      params:
        layer_prefix: normal_analytic_
        position_layer: elevation
        scale: 0.06
        line_width: 0.005
        color: 15600153 # red